# Generated by Django 5.2.13 on 2026-07-07 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0010_site_engineer_workflow'),
        ('systems', '0001_request_under_review_routing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='assigned_review_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_assigned_designs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='main_design_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_design_lead_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='review_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='review_cancel_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='review_cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='sub_design_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_design_lead_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='systems',
            field=models.ManyToManyField(blank=True, related_name='design_requests', to='systems.systemname'),
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft Request'), ('request_under_review', 'Request Under Review'), ('engineer_pending_acknowledgement', 'Engineer Pending Acknowledgement'), ('engineer_in_progress', 'Engineer In Progress'), ('new_request', 'New Request'), ('acknowledged', 'Acknowledged'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('correction_required', 'Correction Required'), ('resubmitted', 'Re-Submitted'), ('verification_pending_acknowledgement', 'Verification Pending Acknowledgement'), ('verification_pending', 'Verification Pending'), ('verification_correction', 'Verification Correction'), ('awaiting_compliance', 'Awaiting Compliance'), ('compliance_pending_acknowledgement', 'Compliance Pending Acknowledgement'), ('compliance_pending', 'Compliance Pending'), ('compliance_correction', 'Compliance Correction'), ('final_approval_pending', 'Final Approval Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=40),
        ),
    ]
