# Generated by Django 5.2.13 on 2026-06-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Genesis Design', max_length=200)),
                ('tagline', models.CharField(default='Design Management System', max_length=255)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, default='info@genesisdesign.local', max_length=254)),
                ('website', models.URLField(blank=True)),
                ('timezone_name', models.CharField(default='Asia/Dhaka', max_length=64)),
            ],
            options={
                'verbose_name_plural': 'company settings',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30, unique=True)),
                ('can_create_project', models.BooleanField(default=False)),
                ('can_create_request', models.BooleanField(default=False)),
                ('can_assign_designer', models.BooleanField(default=False)),
                ('can_review', models.BooleanField(default=False)),
                ('can_verify', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_manage_settings', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'role permissions',
            },
        ),
        migrations.CreateModel(
            name='SLAConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_warning_percent', models.PositiveSmallIntegerField(default=20)),
                ('escalation_level_1_days', models.PositiveSmallIntegerField(default=1)),
                ('escalation_level_2_days', models.PositiveSmallIntegerField(default=3)),
                ('auto_breach_notify', models.BooleanField(default=True)),
                ('count_weekends', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'SLA configuration',
            },
        ),
    ]
