# Generated by Django 5.2.13 on 2026-06-28 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_sidebar_permissions(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    UserSidebarPermission = apps.get_model('core', 'UserSidebarPermission')
    from apps.accounts.sidebar_permissions import get_default_sidebar_for_role

    for user in User.objects.all().iterator():
        defaults = get_default_sidebar_for_role(user.role)
        UserSidebarPermission.objects.create(user=user, **defaults)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_companysettings_file_sharing_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSidebarPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_dashboard', models.BooleanField(default=True)),
                ('nav_projects', models.BooleanField(default=True)),
                ('nav_my_tasks', models.BooleanField(default=False)),
                ('nav_design_library', models.BooleanField(default=False)),
                ('nav_taskboard', models.BooleanField(default=False)),
                ('nav_reports', models.BooleanField(default=False)),
                ('nav_executive', models.BooleanField(default=False)),
                ('nav_leaderboard', models.BooleanField(default=False)),
                ('nav_workload', models.BooleanField(default=False)),
                ('nav_team', models.BooleanField(default=False)),
                ('nav_settings', models.BooleanField(default=False)),
                ('nav_profile', models.BooleanField(default=True)),
                ('nav_kpi', models.BooleanField(default=True)),
                ('nav_notifications', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sidebar_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user sidebar permissions',
            },
        ),
        migrations.RunPython(backfill_sidebar_permissions, noop),
    ]
