from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_requester_my_tasks_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadlineconfiguration',
            name='action_acknowledge_days',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deadlineconfiguration',
            name='action_acknowledge_hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deadlineconfiguration',
            name='action_assign_designer_days',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deadlineconfiguration',
            name='action_assign_designer_hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deadlineconfiguration',
            name='action_accept_assignment_days',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deadlineconfiguration',
            name='action_accept_assignment_hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deadlineconfiguration',
            name='action_hod_review_days',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='deadlineconfiguration',
            name='action_hod_review_hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deadlineconfiguration',
            name='action_send_to_verification_days',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deadlineconfiguration',
            name='action_send_to_verification_hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deadlineconfiguration',
            name='action_verification_ack_days',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deadlineconfiguration',
            name='action_verification_ack_hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deadlineconfiguration',
            name='action_send_to_compliance_days',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deadlineconfiguration',
            name='action_send_to_compliance_hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deadlineconfiguration',
            name='action_compliance_ack_days',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deadlineconfiguration',
            name='action_compliance_ack_hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deadlineconfiguration',
            name='action_compliance_correction_days',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deadlineconfiguration',
            name='action_compliance_correction_hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deadlineconfiguration',
            name='action_mark_complete_days',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deadlineconfiguration',
            name='action_mark_complete_hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
